Add script to build BOOT.BIN for versal
analogdevicesinc/wiki-scripts pull request #19
Opened 2024-03-12 10:00 UTC by AAndrisa

2024-03-12 12:09 UTC, SRaus requested changes

2024-03-12 16:21 UTC, AAndrisa commented
v2: PR changes added

2024-03-12 16:25 UTC, AAndrisa commented
v3: fix indentation

2024-03-12 16:41 UTC, SRaus commented on versal_boot_bin/build_versal_boot_bin.sh
> +	cp u-boot.elf ../../$OUTPUT_DIR/u-boot.elf
Just make all of the copy commands consistent - see #61, #68, #76 etc (all inside or all outside parenthesis)
I think that on line #68 is  needed one single level up (../) not two (../../). Please check.

2024-03-13 08:14 UTC, AAndrisa commented
v4: update cp path

2024-03-13 11:46 UTC, SRaus approved these changes

2024-03-13 14:29 UTC, merged